name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: 3.8.5
    steps:
    - uses: actions/checkout@v2
    - name: setup virtual environment
      run: |
        make setup
    - name: check python version
      run: |
        make test-venv
    - name: black formatting
      run: |
        make black
    - name: check clean target
      run: |
        make clean
